remote_theme: hydecorp/hydejack@v9.0.4

title: Austin Huang

# Default:
tagline: A young JavaScript developer who writes chatbots and stories in Montreal.
accent_image: '/assets/sidebar-bg.jpg'
accent_color: '#bada55'
background: '#bada55'

# Remembrance Day:
# tagline: On November 11, We Remember.
# accent_color: '#d8002b'
# accent_image: /assets/poppy.jpg
# background: '#d8002b'

url: https://austinhuang.me

author:
  name:  Austin Huang
  email: im@austinhuang.me
  social:
    email: mailto:im@austinhuang.me
    github: austinhuang0131
    reddit: austinhuang
    telegram: austinhuang

no_google_fonts: true
font: Noto Sans, Trebuchet MS, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Georgia, serif

exclude:
  - .jekyll-cache
  - .sass-cache
  - vendor
  - Gemfile
  - Gemfile.lock
include:
  - assets
